services:
  postgres:
    image: postgres:15
    container_name: sanya-postgres
    restart: always
    environment:
      POSTGRES_USER: nicron
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sanya-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - postgres

volumes:
  pgdata: